
on:
  push:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20 for x64
        uses: actions/setup-java@v4
        with:
          java-version: 'corretto-20'
          architecture: x64
      - name: Build with Maven
        run: mvn test
#    with:
#      java-version: '20'
#      distribution: 'correto'
#      architecture: x64

